---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1dd5788jkk97pcmzsgvkha7hhksjhhfv30dusa6pwjhcclyy06qxsqqyukz"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1dd5788jkk97pcmzsgvkha7hhksjhhfv30dusa6pwjhcclyy06qxsqqyukz"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1dd5788jkk97pcmzsgvkha7hhksjhhfv30dusa6pwjhcclyy06qxsqqyukz"
