apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8xZrp1Z8e4iJsfdd/y6fXIJxTHkCAQ==,iv:AMp0IYIUToNEba+uNzdhj2jNy0E6qj5OqKPvvzCeNBY=,tag:U/1WBfBz4/2vEArDIzr7xg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4JopPPEvm35czctLUK2EqT46wCHwELkeNvhu85AmVVnJUPp7,iv:75o3zadCfMykmdkHdjkT2rPJG8oy0yS+JwSz/LUhsJ0=,tag:jjg9CNr8rK8ohx3rLcDChg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:f1cL/H0zlVef1w==,iv:NZKY066Yz6Zea4VJTgP0KBptiTodsMdkIbRgI4zy6uQ=,tag:iz0QOF8DpKVFtz3xhNyMUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dd5788jkk97pcmzsgvkha7hhksjhhfv30dusa6pwjhcclyy06qxsqqyukz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dnNhYkZKZ09tUUFEZ1d2
            WmQ3QisvcjNPZk95K2VvNGFqQnBMQXJMdmdBCm9PSlNaY2JBSjBlRHJwU2FBaXFn
            VUp6RGRXZVIzWmRjMzRrNGlNS0NTWkkKLS0tIEp4QnhtUzlTQjhjcE5UdFhkNmMw
            dmFhQVd1L0FkUFVKd0VFRGJiWTBJc2sK29YBNhJovv7IC/Q37sAzH48Ku7ummtgO
            o4BIkSeQkAJVsfFlk/RqV6n9i9Dxa35jKmVHjdGGAxJqpfVC46G/rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-31T06:45:48Z"
    mac: ENC[AES256_GCM,data:SHA4LAAjwnLgM+QjZ+arajmiOBVqNsfqxzu/6Wkk8pr1GMja4Fk7I0QUQZtZC54VJnL860RoNlMYlAFiWtJtkJFqNsc+5MIy0d4Aasfr6XC9eZzl6+wkbatoMG89XGKm8dKNcoajWeC5L6HnwArc1tQfja/UdhbU3fi1Xm/5cBs=,iv:qJMbrYAtZeCadwrTLjk/gIizQYyOozz7ndtsygABetQ=,tag:NwyM4mmg+6UadhuOOqO5bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
